### ISSUE TITLE
upload a folder makes a .workspace/null folder

### ISSUE THREAD

**Issue by ryestew** [bunsenstraat/remix-desktop#1]
Uploading a folder makes a folder named null - probably not a great choice of name

<img width="205" alt="image" src="https://github.com/bunsenstraat/remix-desktop/assets/6050001/c538f5e4-c7c7-4178-9fb9-aa34719eccaa">

**Comment by ryestew** [comment]
and when uploading a file it also goes in the ./workspaces/null folder
But in either case should these buttons be in the desktop version - because no upload is possible (everything is local).

**Comment by bunsenstraat** [comment]
you're right I will take them out!!

**Comment by bunsenstraat** [comment]
fixed in 0.0.7
